
"""initial_orbit_schema

Revision ID: 0252b66d5ffd
Revises: 
Create Date: 2026-03-03 10:52:07.272398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0252b66d5ffd'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('brain_rot_level', sa.Enum('CHILL', 'MID', 'COOKED', name='brainrotlevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_tasks_id'), 'study_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_study_tasks_subject'), 'study_tasks', ['subject'], unique=False)
    op.create_index(op.f('ix_study_tasks_title'), 'study_tasks', ['title'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_tasks_title'), table_name='study_tasks')
    op.drop_index(op.f('ix_study_tasks_subject'), table_name='study_tasks')
    op.drop_index(op.f('ix_study_tasks_id'), table_name='study_tasks')
    op.drop_table('study_tasks')
    # ### end Alembic commands ###


